### ISSUE TITLE
Automation problem

### ISSUE THREAD

**Issue by samuelemarazzita** [thunderbird/homebridge-w215#3]
Hello, seems the plug has problem with automation on apple home app. When I create an automation to turn on the plug ad certain time of the day, the plug doesn't turn on. On command line I haven't many log just a simple ERROR when trying to turn it on.

Trying to control it manually works perfectly (with just few seconds lag)

**Comment by ianmichell** [comment]
Can you post the error up please.

**Comment by samuelemarazzita** [comment]
Unfortunately there is no other detail than a generic ERROR.

**Comment by ianmichell** [comment]
I've made a new release. Let me know if anything gets resolved.
