### ISSUE TITLE
Error Logs

### ISSUE THREAD

**Issue by turbidWaters** [thunderbird/homebridge-w215#5]
the following are lines from my Homebridge Logs pertinent to the homebridge-w215 plug-in:
__
Jul 16 08:29:31 pi3 homebridge[9250]: error: TypeError: Cannot read property 'nodeValue' of null
Jul 16 08:29:31 pi3 homebridge[9250]: at readResponseValue (/usr/local/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
Jul 16 08:29:31 pi3 homebridge[9250]: at /usr/local/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
Jul 16 08:29:31 pi3 homebridge[9250]: at tryCallOne (/usr/local/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
Jul 16 08:29:31 pi3 homebridge[9250]: at /usr/local/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
Jul 16 08:29:31 pi3 homebridge[9250]: at flush (/usr/local/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
Jul 16 08:29:31 pi3 homebridge[9250]: at _combinedTickCallback (internal/process/next_tick.js:73:7)
Jul 16 08:29:31 pi3 homebridge[9250]: at process._tickCallback (internal/process/next_tick.js:104:9)
Jul 16 08:29:31 pi3 homebridge[9250]: error: TypeError: Cannot read property 'nodeValue' of null
Jul 16 08:29:31 pi3 homebridge[9250]: at readResponseValue (/usr/local/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
Jul 16 08:29:31 pi3 homebridge[9250]: at /usr/local/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
Jul 16 08:29:31 pi3 homebridge[9250]: at tryCallOne (/usr/local/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
Jul 16 08:29:31 pi3 homebridge[9250]: at /usr/local/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
Jul 16 08:29:31 pi3 homebridge[9250]: at flush (/usr/local/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
Jul 16 08:29:31 pi3 homebridge[9250]: at _combinedTickCallback (internal/process/next_tick.js:73:7)
Jul 16 08:29:31 pi3 homebridge[9250]: at process._tickCallback (internal/process/next_tick.js:104:9)
Jul 16 08:29:31 pi3 homebridge[9250]: error: TypeError: Cannot read property 'nodeValue' of null
Jul 16 08:29:31 pi3 homebridge[9250]: at readResponseValue (/usr/local/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
Jul 16 08:29:31 pi3 homebridge[9250]: at /usr/local/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
Jul 16 08:29:31 pi3 homebridge[9250]: at tryCallOne (/usr/local/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
Jul 16 08:29:31 pi3 homebridge[9250]: at /usr/local/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
Jul 16 08:29:31 pi3 homebridge[9250]: at flush (/usr/local/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
Jul 16 08:29:31 pi3 homebridge[9250]: at _combinedTickCallback (internal/process/next_tick.js:73:7)
Jul 16 08:29:31 pi3 homebridge[9250]: at process._tickCallback (internal/process/next_tick.js:104:9)
__
This is my config.json:

{
                        "accessory": "w215",
                        "name": "Guest Geyser",
                        "host": "172.20.1.115",
                        "username": "admin",
                        "password": "xxxxxx"
                },
                {
                        "accessory": "w215",
                        "name": "Bedroom AC",
                        "host": "172.20.1.116",
                        "username": "admin",
                        "password": "xxxxxx"
                },
                {
                        "accessory": "w215",
                        "name": "Guest AC",
                        "host": "172.20.1.117",
                        "username": "admin",
                        "password": "xxxxxx"
                }

While the "multiple plugs single output" issue still persists, I would like to know if there is **something else** wrong with my config. Any help is appreciated. Thanks.

**Comment by ianmichell** [comment]
New release should resolve this.
